-- Disable RLS on tables for Guest Mode / MVP testing
ALTER TABLE teacher_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE parent_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE child_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE connection_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE child_profile DISABLE ROW LEVEL SECURITY;
